// Rule 1-3: five curated matches per week, no swiping, no on-demand
// refresh. Batches are generated by the matching engine (see
// src/lib/matching/engine.ts) — this page only reads the current
// batch and lets the user express interest in up to 2 of them.

import { redirect } from "next/navigation";
import { Interlace } from "@/components/Interlace";
import { MatchBatch } from "@/components/MatchBatch";
import type { MatchCandidate } from "@/components/MatchCard";
import { auth } from "@/lib/auth";
import { query } from "@/lib/db";

type CandidateRow = {
  batch_id: string;
  matched_user_id: string;
  full_name: string | null;
  date_of_birth: string | null;
  occupation: string | null;
  location: string | null;
  bio: string | null;
};

function ageFromDob(dateOfBirth: string | null): number | null {
  if (!dateOfBirth) return null;
  const dob = new Date(dateOfBirth);
  const now = new Date();
  let age = now.getFullYear() - dob.getFullYear();
  const hadBirthday =
    now.getMonth() > dob.getMonth() ||
    (now.getMonth() === dob.getMonth() && now.getDate() >= dob.getDate());
  if (!hadBirthday) age -= 1;
  return age;
}

export default async function MatchesPage() {
  const session = await auth();
  if (!session?.user) redirect("/login");
  const userId = session.user.id;

  const [activeMutual] = await query<{ id: string }>(
    `SELECT id FROM mutual_matches WHERE status = 'active' AND (user_a_id = ? OR user_b_id = ?) LIMIT 1`,
    [userId, userId]
  );

  if (activeMutual) {
    return (
      <main className="px-6 py-10 max-w-2xl mx-auto">
        <h1 className="font-display text-3xl mb-4">You have an active match</h1>
        <p className="font-sans text-sm text-[var(--paper-dim)]">
          New batches only arrive when you&rsquo;re between matches. Head to
          your{" "}
          <a href="/dashboard/relationship" className="underline text-[var(--jade)]">
            relationship
          </a>{" "}
          tab.
        </p>
      </main>
    );
  }

  const rows = await query<CandidateRow>(
    `SELECT m.batch_id, m.matched_user_id,
            u.full_name, u.date_of_birth, u.occupation, u.location, u.bio
     FROM matches m
     JOIN users u ON u.id = m.matched_user_id
     WHERE m.user_id = ? AND m.expires_at > NOW()
     ORDER BY m.created_at ASC`,
    [userId]
  );

  const currentBatchId = rows[0]?.batch_id ?? null;
  const batchRows = rows.filter((r) => r.batch_id === currentBatchId);

  let interestedIds: string[] = [];
  if (currentBatchId) {
    const interests = await query<{ matched_user_id: string }>(
      `SELECT matched_user_id FROM interests WHERE user_id = ? AND batch_id = ?`,
      [userId, currentBatchId]
    );
    interestedIds = interests.map((i) => i.matched_user_id);
  }

  const candidates: MatchCandidate[] = batchRows.map((r) => ({
    matchedUserId: r.matched_user_id,
    name: r.full_name ?? "Someone new",
    age: ageFromDob(r.date_of_birth),
    occupation: r.occupation,
    location: r.location,
    bio: r.bio,
  }));

  return (
    <main className="px-6 py-10 max-w-2xl mx-auto">
      <h1 className="font-display text-3xl mb-1">Your five, this week</h1>
      <p className="font-sans text-sm text-[var(--paper-dim)] mb-2 max-w-lg">
        No swiping, no browsing beyond this. Express interest in up to two —
        if it&rsquo;s mutual, you&rsquo;ll unlock chat right away.
      </p>
      <p className="font-sans text-xs text-[var(--paper-dim)] opacity-60 mb-8">
        If nothing becomes mutual this week, your next set of five arrives
        in 7 days — not sooner.
      </p>

      {candidates.length === 0 ? (
        <div className="bg-paper text-[var(--text-on-paper)] rounded-xl px-6 py-12 text-center">
          <p className="font-sans text-sm opacity-70">
            Your next batch of five is being put together — check back
            shortly.
          </p>
        </div>
      ) : (
        <MatchBatch
          batchId={currentBatchId!}
          candidates={candidates}
          initialInterestedIds={interestedIds}
        />
      )}

      <div className="flex justify-center my-10">
        <Interlace className="opacity-50" />
      </div>

      <p className="font-sans text-xs text-center text-[var(--paper-dim)] opacity-60">
        We keep this list small on purpose — knowing there are more
        people &ldquo;out there&rdquo; is exactly what stops people from
        giving a real chance to who&rsquo;s in front of them.
      </p>
    </main>
  );
}
